### ISSUE TITLE
Random failures (not exhausting socket input)

### ISSUE THREAD

**Issue by ctrochalakis** [dex4er/nss-docker#2]
Hello & thank you for nss-docker,

I was getting random resolve failures (~ 1 in 10 requests). After a bit of debugging I traced it down to the `read()` call on the API socket. The current code performs a single `read()` instead of exhausting the socket data. So, if the response is split in more than one batch, and the ip address is not in that first batch, the resolution fails.

**Comment by cristoper** [comment]
I'm using release 0.02 from the Debian repositories and this bug has been giving me a headache. Thank you for tracking it down and fixing it, @ctrochalakis!

@dex4er, any plans to update the Debian package? (Installing from git in the mean time is no problem.)
